### ISSUE TITLE
Make accommodation page responsive

### ISSUE THREAD

**Issue by VitaliyMinaev** [VitaliyMinaev/PropertySearch#26]
Accommodation cards start to look really bad at some screen resolutions, for example: 
![image](https://user-images.githubusercontent.com/87979065/228245695-5b98706e-878e-4ef8-bed2-97c91444eff4.png)

Bad media-query Transitions:
- [x] 992px -> 991px
- [x] 768px -> 767px

Change media-queries and make ui better!

**Comment by FarrukhTahir5** [comment]
@VitaliyMinaev Please Assign it to me
