### ISSUE TITLE
Change title for accommodation tab

### ISSUE THREAD

**Issue by VitaliyMinaev** [VitaliyMinaev/PropertySearch#27]
The home page and privacy policy have their own tab title:
![image](https://user-images.githubusercontent.com/87979065/228248359-a099e335-f291-4550-9baa-fa01a736dcd6.png)

But the accommodation page does not: 
![image](https://user-images.githubusercontent.com/87979065/228248943-295ce3f9-0f62-4491-b001-e02dee0724f6.png)

Add title for accommodation page

**Comment by ramonpjls** [comment]
hi, i will like to solve this

**Comment by praj-pawar** [comment]
@VitaliyMinaev Hey again! I'd like to fix this bug. Could you assign it to me?
